const PROJECTS = {
  professional: [
    {
      id: 'meowwolf',
      year: '2025',
      title: 'Meow Wolf',
      meta: 'Niantic Spatial · Mobile AR · Unity',
      blurb: 'AR Quest experience proof of concept for Meow Wolf\'s established brand.',
      thumb: null,
      involvement: 'Designer, flow & UI implementation. Took the client brief, synthesised high-level goals, and produced detailed app flow and UI. Iterated with the team, implemented UI, and worked with an artist on assets tailored to Meow Wolf\'s distinctive voice. Delivered and tested with a small end-user group — client and users were very happy with the result.',
      links: [
        { label: 'Meow Wolf PR ↗', url: 'https://meowwolf.com/press-releases/meow-wolf-and-niantic-spatial-announce-plans-to-explore-an-expansion-of-the-meow-wolf-universe-p9ql1' },
        { label: 'Niantic PR ↗', url: 'https://www.nianticspatial.com/en/blog/meow-wolf-partnership' },
        { label: 'Reddit ↗', url: 'https://www.reddit.com/r/meowwolf/comments/1qbeydi/niantic_x_meow_wolf_augmented_reality_play_test/' },
      ],
      tags: ['AR', 'Unity', 'UI Design', 'Client Work', 'Shipped'],
    },
    {
      id: 'dynchars',
      year: '2025',
      title: 'AI Hackathon: Dynamic Characters',
      meta: 'Niantic Labs · PC · Unity',
      blurb: 'Order AI characters to construct buildings with an RTS-like interface. Runtime AI image generation.',
      thumb: null,
      involvement: 'Design and prototype. Explored AI-driven character direction using an RTS-style command interface, with runtime AI image generation for dynamic visual feedback.',
      links: [],
      tags: ['AI', 'RTS', 'Unity', 'Prototype'],
    },
    {
      id: 'hiddengems',
      year: '2024',
      title: 'Hidden Gems',
      meta: 'Niantic Labs · Web · 8th Wall',
      blurb: 'Cryptic puzzle game built from user-created Gaussian Splat scans.',
      thumb: null,
      involvement: 'Solo — design, prototype, implementation. Using the internal 8th Wall web engine and Niantic\'s Gaussian Splats system, designed a puzzle challenge where users take their own scans and craft cryptic-style puzzles from them.',
      links: [],
      tags: ['Web', '8th Wall', 'Gaussian Splats', 'Solo', 'Puzzle'],
    },
    {
      id: 'scaniverse',
      year: '2024',
      title: 'Into the Scaniverse',
      meta: 'Niantic Labs · WebVR · 8th Wall → Meta Quest',
      blurb: 'Browse a globe populated with user-created Gaussian Splat scans.',
      thumb: 'assets/images/niantic/image.png',
      involvement: 'Design, prototype, UX, implementation. Team of ~10. Designed the 3D environment and UX — a globe covered in pins that users rotate and zoom. Designed a feed system for surfacing relevant and interesting splats. Helped iterate the overall experience and ship it to the Meta Quest store.',
      links: [
        { label: 'Meta Quest ↗', url: 'https://www.meta.com/en-gb/experiences/into-the-scaniverse/8575253579256191/' },
        { label: 'Niantic Labs ↗', url: 'https://nianticlabs.com/news/into-the-scaniverse-native-app-meta-quest?hl=en' },
      ],
      tags: ['WebVR', '8th Wall', 'Gaussian Splats', 'Meta Quest', 'Shipped'],
    },
    {
      id: 'dyndirector',
      year: '2024',
      title: 'AI Hackathon: Dynamic Director',
      meta: 'Niantic Labs · Mobile · Unity',
      blurb: 'AI tells you how to direct actors, and you film them.',
      thumb: null,
      involvement: 'Solo design and prototype. Explored AI as a real-time director\'s assistant — generating staging instructions while the user captures footage of real people.',
      links: [],
      tags: ['AI', 'Mobile', 'Unity', 'Solo', 'Prototype'],
    },
    {
      id: 'contraptions',
      year: '2024',
      title: 'Contraptions',
      meta: 'Niantic Labs · Lenovo A3 AR glasses · Unity',
      blurb: 'Marble roll tracks and colocated multiplayer for Qualcomm\'s XR2 spec glasses.',
      thumb: null,
      involvement: 'Design, prototype, implementation. Small team (~3). Designed the light gameplay, prototyped, and worked with an artist to develop a readable visual style and integrate assets.',
      links: [
        { label: 'Trailer ↗', url: 'https://youtu.be/tYCWT4i03yU' },
      ],
      tags: ['AR Glasses', 'Qualcomm XR2', 'Multiplayer', 'Lenovo', 'Unity'],
    },
    {
      id: 'pogo',
      year: '2023',
      title: 'Pokémon GO Prototypes',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'Multiple design and prototype contributions. NDA.',
      thumb: 'assets/images/niantic/niantic_logo_2020.png',
      involvement: 'Design and prototyping across multiple projects. Details redacted per NDA.',
      links: [],
      tags: ['Mobile AR', 'Pokémon GO', 'NDA', 'Unity'],
    },
    {
      id: 'heavymetal',
      year: '2022',
      title: 'Heavy Metal Prototype',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'Prototype contributions. NDA.',
      thumb: 'assets/images/niantic/transformers-heavy-metal.png',
      involvement: 'Design and prototype. Details redacted per NDA.',
      links: [],
      tags: ['Mobile AR', 'NDA', 'Unity'],
    },
    {
      id: 'peridot',
      year: '2022',
      title: 'Peridot Multiplayer Prototype',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'VPS-colocated dog-park multiplayer experience for the Peridot AR pet sim.',
      thumb: 'assets/images/niantic/screenshot-2025-07-29-205827.png',
      involvement: 'Solo design and prototype. Designed a dog-park-like multiplayer experience using VPS to colocate players in the real world. Considered real-world meeting conditions — traffic times and privacy. Developed the prototype and filmed a demo using a rig of 3 mobile phones.',
      links: [],
      tags: ['Mobile AR', 'VPS', 'Multiplayer', 'Solo', 'Unity'],
    },
    {
      id: 'destmars',
      year: '2021',
      title: 'Destination Mars',
      meta: 'NZXR · Tablet · Unreal',
      blurb: 'Theatre experience — ~30–50 participants interact via tablet alongside live actors.',
      thumb: null,
      involvement: 'Design, prototype, gameplay and UI implementation. Built an interactive tablet layer for a live theatre performance where audience members affect the story alongside on-stage actors.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=v_Ou1selGjc' },
      ],
      tags: ['Tablet', 'Unreal', 'Theatre', 'Multiplayer', 'LBE'],
    },
    {
      id: 'craneoff',
      year: '2021',
      title: 'Great Crane Cake Off',
      meta: 'NZXR · Qualcomm Snapdragon Spaces · Unity',
      blurb: 'Use your head-mounted crane to assemble wobbly celebration cakes.',
      thumb: null,
      involvement: 'Design, prototype, gameplay implementation. Physics-based head-tracking game built on Qualcomm Snapdragon Spaces to showcase early AR glasses hardware.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=KHmyQyeYEQY' },
      ],
      tags: ['AR Glasses', 'Snapdragon Spaces', 'Physics', 'Unity'],
    },
    {
      id: 'storyxr',
      year: '2021',
      title: 'StoryXR',
      meta: 'NZXR · Mobile AR · Unity',
      blurb: 'Platform for user-created location-based experiences.',
      thumb: null,
      involvement: 'Design, prototype, implementation. Built a creator platform enabling users to author and share location-based AR experiences.',
      links: [],
      tags: ['Mobile AR', 'Location Based', 'Unity', 'Platform'],
    },
    {
      id: 'axon',
      year: '2020',
      title: 'Axon Police De-escalation Training',
      meta: 'NZXR · VR · Quest · Unity',
      blurb: 'Natural language immersive narrative VR training experience.',
      thumb: null,
      involvement: 'Design, prototype, gameplay implementation, dialogue writing. Built a VR scenario for police training using natural language input to drive branching narrative outcomes in immersive real-world situations.',
      links: [],
      tags: ['VR', 'Quest', 'Narrative', 'Training', 'NLP', 'Unity'],
    },
    {
      id: 'robotwar',
      year: '2019',
      title: 'Robot War LBE',
      meta: 'Magic Leap / Weta Workshop · Magic Leap · Unity',
      blurb: 'Defend and repair your ship on another planet. Location-based, colocated multiplayer.',
      thumb: null,
      involvement: 'Design and prototype gameplay for a location-based multiplayer experience using the Magic Leap headset.',
      links: [],
      tags: ['Magic Leap', 'LBE', 'Multiplayer', 'Unity'],
    },
    {
      id: 'society',
      year: '2019',
      title: 'The Society of Not Getting Along Together Nicely',
      meta: 'Magic Leap / Weta Workshop · Magic Leap · Unity',
      blurb: 'High tea toy and arena shooter. Colocated multiplayer. Finished, unshipped.',
      thumb: null,
      involvement: 'Design, prototype and implementation of toys and gameplay. A colocated multiplayer MR experience mixing genteel tea party mechanics with arena combat.',
      links: [],
      tags: ['Magic Leap', 'Multiplayer', 'MR', 'Unity', 'Unshipped'],
    },
    {
      id: 'spatialpuzzle',
      year: '2018',
      title: 'Spatial Puzzle Prototype',
      meta: 'Magic Leap / Weta Workshop · Magic Leap · Unity',
      blurb: 'Dynamically assembled challenges that fit your room.',
      thumb: null,
      involvement: 'Solo design and prototype. Explored challenges that adapted dynamically to the player\'s physical space — puzzles that understood and used the geometry of your room.',
      links: [],
      tags: ['Magic Leap', 'Spatial', 'Puzzle', 'Solo', 'Unity'],
    },
    {
      id: 'invaders',
      year: '2015–19',
      title: "Dr Grordbort's Invaders",
      meta: 'Magic Leap / Weta Workshop · Magic Leap One · Unity',
      blurb: 'Large budget Mixed Reality shooter — robots climb out of your walls.',
      thumb: 'assets/images/invaders/hero-drg-large_3x.jpg',
      involvement: 'Designing, prototyping, testing — creating novel 3D mixed-reality interfaces, puzzles, missions, systems and environments. Many gameplay prototypes for a cutting-edge in-development headset, working across Magic Leap and Weta Workshop.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=KHmyQyeYEQY' },
      ],
      tags: ['Magic Leap', 'MR Shooter', 'Weta Workshop', 'Unity', 'Shipped'],
    },
    {
      id: 'poe',
      year: '2011–15',
      title: 'Path of Exile',
      meta: 'Grinding Gear Games · PC · In-house engine',
      blurb: 'Diablo-inspired online Action RPG. PC Game of the Year 2013.',
      thumb: 'assets/images/path-of-exile/path-of-exile-button-1503612705551.jpg',
      involvement: 'Sole level designer from pre-alpha through release and several expansions. Created all levels — working with and refining the generation system to craft areas, rooms and topologies across diverse themes. Designed and implemented missions, quests, NPCs, dialogue and enemy encounters.',
      links: [
        { label: 'Trailer ↗', url: 'https://youtu.be/dURQBqMiwIk' },
        { label: 'Environments ↗', url: 'https://www.youtube.com/watch?v=f1I0QSF6f94' },
        { label: 'Steam ↗', url: 'https://store.steampowered.com/app/238960/Path_of_Exile/' },
      ],
      tags: ['PC', 'ARPG', 'Level Design', 'Live Service', 'Sole Designer', 'Shipped'],
    },
  ],

  personal: [
    {
      id: 'gravityecho',
      year: '2025',
      title: 'Gravity Echo',
      meta: 'GMTK Game Jam 2025 · Web · Unity',
      blurb: 'Escape the planet before a catastrophe triggers a time loop.',
      thumb: null,
      involvement: 'Team lead, design, implementation. Recruited team members from GMTK and local discords, coordinating across timezones and varied experience levels. Selected artists whose portfolios matched a specific art style vision. Reworked 3D art to make it game-ready. Wrote all code and handled most of the implementation.',
      links: [
        { label: 'Play on itch.io ↗', url: 'https://thatnzguy.itch.io/gravityecho' },
      ],
      tags: ['Game Jam', 'Unity', 'Team Lead', 'Web', 'Shipped'],
    },
    {
      id: 'vigilance',
      year: '<2007',
      title: 'dod_vigilance',
      meta: 'Day of Defeat · PC · Source',
      blurb: 'Custom WWII FPS map. 70,000+ downloads. Top 10 most-played DoD custom maps.',
      thumb: 'assets/images/maps/vigilance_overview.jpg',
      involvement: 'Solo development. Created for both the Half-Life 1 mod Day of Defeat and the Half-Life 2 mod Day of Defeat: Source. Accumulated over 70,000 downloads and ranked among the top 10 most-played custom maps in the community.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=shRhWy4hro4' },
      ],
      tags: ['Level Design', 'Source', 'Solo', 'Modding', 'Community'],
    },
  ],
};
