const PROJECTS = {
  professional: [
    {
      id: 'meowwolf',
      year: '2025',
      title: 'Meow Wolf',
      meta: 'Niantic Spatial · Mobile AR · Unity',
      blurb: 'AR Quest experience proof of concept for Meow Wolf\'s established brand.',
      thumb: 'assets/images/meow-wolf/Screenshot 2026-03-24 112326.png',
      highlight: true,
      rank: 100,
      involvement: 'Designer, flow & UI implementation. Took the client brief, synthesised high-level goals, and produced detailed app flow and UI. Iterated with the team, implemented UI, and worked with an artist on assets tailored to Meow Wolf\'s distinctive voice. Delivered and tested with a small end-user group — client and users were very happy with the result.',
      links: [
        { label: 'Meow Wolf PR ↗', url: 'https://meowwolf.com/press-releases/meow-wolf-and-niantic-spatial-announce-plans-to-explore-an-expansion-of-the-meow-wolf-universe-p9ql1' },
        { label: 'Niantic PR ↗', url: 'https://www.nianticspatial.com/en/blog/meow-wolf-partnership' },
        { label: 'Reddit ↗', url: 'https://www.reddit.com/r/meowwolf/comments/1qbeydi/niantic_x_meow_wolf_augmented_reality_play_test/' },
      ],
      tags: ['AR', 'Unity', 'UI Design', 'Client Work', 'Shipped'],
    },
    {
      id: 'scaniverse',
      year: '2024',
      title: 'Into the Scaniverse',
      meta: 'Niantic Labs · WebVR · 8th Wall → Meta Quest',
      blurb: 'Browse a globe populated with user-created Gaussian Splat scans.',
      thumb: 'assets/images/scaniverse/hero.webp',
      youtube: 'yJ-5Qz3nHpM',
      highlight: true,
      rank: 90,
      involvement: 'Design, prototype, UX, implementation. Team of ~10. Designed the 3D environment and UX — a globe covered in pins that users rotate and zoom. Designed a feed system for surfacing relevant and interesting splats. Helped iterate the overall experience and ship it to the Meta Quest store.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=yJ-5Qz3nHpM' },
        { label: 'Meta Quest ↗', url: 'https://www.meta.com/en-gb/experiences/into-the-scaniverse/8575253579256191/' },
        { label: 'Niantic Labs ↗', url: 'https://nianticlabs.com/news/into-the-scaniverse-native-app-meta-quest?hl=en' },
      ],
      tags: ['WebVR', '8th Wall', 'Gaussian Splats', 'Meta Quest', 'Shipped'],
    },
    {
      id: 'contraptions',
      year: '2024',
      title: 'Contraptions',
      meta: 'Niantic Labs · Lenovo A3 AR glasses · Unity',
      blurb: 'Marble roll tracks and colocated multiplayer for Qualcomm\'s XR2 spec glasses.',
      thumb: 'assets/images/contraptions/thumb.jpg',
      youtube: 'tYCWT4i03yU',
      highlight: true,
      rank: 75,
      involvement: 'Design, prototype, implementation. Small team (~3). Designed the light gameplay, prototyped, and worked with an artist to develop a readable visual style and integrate assets.',
      links: [
        { label: 'Trailer ↗', url: 'https://youtu.be/tYCWT4i03yU' },
      ],
      tags: ['AR Glasses', 'Qualcomm XR2', 'Multiplayer', 'Lenovo', 'Unity'],
    },
    {
      id: 'hiddengems',
      year: '2024',
      title: 'Hidden Gems',
      meta: 'Niantic Labs · Web · 8th Wall',
      blurb: 'Cryptic puzzle game built from user-created Gaussian Splat scans.',
      thumb: 'assets/images/hidden-gems/Screenshot 2026-03-24 111656.png',
      youtube: 'FqXPhB1Uwjg',
      highlight: false,
      rank: 35,
      involvement: 'Solo — design, prototype, implementation. Using the internal 8th Wall web engine and Niantic\'s Gaussian Splats system, designed a puzzle challenge where users take their own scans and craft cryptic-style puzzles from them.',
      links: [
        { label: 'Trailer ↗', url: 'https://youtu.be/FqXPhB1Uwjg' },
        { label: 'Creation ↗', url: 'https://youtu.be/b_6xjW09N3Y' },
      ],
      tags: ['Web', '8th Wall', 'Gaussian Splats', 'Solo', 'Puzzle'],
    },
    {
      id: 'pogo',
      year: '2023',
      title: 'Pokémon GO Prototypes',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'Multiple design and prototype contributions. NDA.',
      thumb: 'assets/images/niantic/image.png',
      highlight: false,
      rank: 25,
      involvement: 'Design and prototyping across multiple projects. Details redacted per NDA.',
      links: [],
      tags: ['Mobile AR', 'Pokémon GO', 'NDA', 'Unity'],
    },
    {
      id: 'heavymetal',
      year: '2022',
      title: 'Heavy Metal Prototype',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'Prototype contributions. NDA.',
      thumb: 'assets/images/niantic/transformers-heavy-metal.png',
      highlight: false,
      rank: 20,
      involvement: 'Design and prototype. Details redacted per NDA.',
      links: [],
      tags: ['Mobile AR', 'NDA', 'Unity'],
    },
    {
      id: 'peridot',
      year: '2022',
      title: 'Peridot Multiplayer Prototype',
      meta: 'Niantic Labs · Mobile AR · Unity',
      blurb: 'VPS-colocated dog-park multiplayer experience for the Peridot AR pet sim.',
      thumb: 'assets/images/niantic/image-1.png',
      highlight: false,
      rank: 40,
      involvement: 'Solo design and prototype. Designed a dog-park-like multiplayer experience using VPS to colocate players in the real world. Considered real-world meeting conditions — traffic times and privacy. Developed the prototype and filmed a demo using a rig of 3 mobile phones.',
      links: [],
      tags: ['Mobile AR', 'VPS', 'Multiplayer', 'Solo', 'Unity'],
    },
    {
      id: 'destmars',
      year: '2021',
      title: 'Destination Mars',
      meta: 'NZXR · Tablet · Unreal',
      blurb: 'Theatre experience — ~30–50 participants interact via tablet alongside live actors.',
      thumb: 'assets/images/destmars/thumb.jpg',
      youtube: 'v_Ou1selGjc',
      highlight: true,
      rank: 70,
      involvement: 'Design, prototype, gameplay and UI implementation. Built an interactive tablet layer for a live theatre performance where audience members affect the story alongside on-stage actors.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=v_Ou1selGjc' },
      ],
      tags: ['Tablet', 'Unreal', 'Theatre', 'Multiplayer', 'LBE'],
    },
    {
      id: 'craneoff',
      year: '2021',
      title: 'Great Crane Cake Off',
      meta: 'NZXR · Qualcomm Snapdragon Spaces · Unity',
      blurb: 'Use your head-mounted crane to assemble wobbly celebration cakes.',
      thumb: 'assets/images/craneoff/thumb.jpg',
      youtube: 'KHmyQyeYEQY',
      highlight: true,
      rank: 65,
      involvement: 'Design, prototype, gameplay implementation. Physics-based head-tracking game built on Qualcomm Snapdragon Spaces to showcase early AR glasses hardware.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=KHmyQyeYEQY' },
      ],
      tags: ['AR Glasses', 'Snapdragon Spaces', 'Physics', 'Unity'],
    },
    {
      id: 'storyxr',
      year: '2021',
      title: 'StoryXR',
      meta: 'NZXR · Mobile AR · Unity',
      blurb: 'Platform for user-created location-based experiences.',
      thumb: null,
      youtube: 'ELKgKeZT9OE',
      highlight: true,
      rank: 55,
      involvement: 'Design, prototype, implementation. Built a creator platform enabling users to author and share location-based AR experiences.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=ELKgKeZT9OE' },
      ],
      tags: ['Mobile AR', 'Location Based', 'Unity', 'Platform'],
    },
    {
      id: 'axon',
      year: '2020',
      title: 'Axon Police De-escalation Training',
      meta: 'NZXR · VR · Quest · Unity',
      blurb: 'Natural language immersive narrative VR training experience.',
      thumb: null,
      highlight: false,
      rank: 15,
      involvement: 'Design, prototype, gameplay implementation, dialogue writing. Built a VR scenario for police training using natural language input to drive branching narrative outcomes in immersive real-world situations.',
      links: [],
      tags: ['VR', 'Quest', 'Narrative', 'Training', 'NLP', 'Unity'],
    },
    {
      id: 'grordbattle',
      year: '2019',
      title: 'Grordbattle',
      meta: 'Magic Leap / Weta Workshop · Magic Leap · Unity',
      blurb: 'Mixed-reality shared-space multiplayer — wear virtual masks, serve tea, scones, and violence.',
      thumb: null,
      youtube: 'y4VTxpDNeWk',
      highlight: false,
      rank: 70,
      involvement: 'Game design in a team of ~10. Design, prototype, implementation of interactions, toys and gameplay. "It was hands down the best thing we played at this year\'s Game Developers Conference!" — Adam Savage\'s Tested.',
      links: [
        { label: 'Review ↗', url: 'https://www.youtube.com/watch?v=y4VTxpDNeWk' },
      ],
      tags: ['Magic Leap', 'MR', 'Multiplayer', 'GDC', 'Unity'],
    },
    {
      id: 'lbe2019',
      year: '2019',
      title: 'Location Based Experience',
      meta: 'Magic Leap / Weta Workshop · Magic Leap · Unity',
      blurb: 'Location-based colocated multiplayer experience.',
      thumb: null,
      highlight: false,
      rank: 12,
      involvement: 'Design and prototype gameplay.',
      links: [],
      tags: ['Magic Leap', 'LBE', 'Multiplayer', 'Unity'],
    },
    {
      id: 'invaders',
      year: '2015–19',
      title: "Dr Grordbort's Invaders",
      meta: 'Magic Leap / Weta Workshop · Magic Leap One · Unity',
      blurb: 'Large budget Mixed Reality shooter — robots climb out of your walls.',
      thumb: 'assets/images/invaders/hero-drg-large_3x.jpg',
      youtube: '45ZHNq9_7eY',
      highlight: true,
      rank: 85,
      involvement: 'Designing, prototyping, testing — creating novel 3D mixed-reality interfaces, puzzles, missions, systems and environments. Many gameplay prototypes for a cutting-edge in-development headset, working across Magic Leap and Weta Workshop.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=45ZHNq9_7eY' },
      ],
      tags: ['Magic Leap', 'MR Shooter', 'Weta Workshop', 'Unity', 'Shipped'],
    },
    {
      id: 'poe',
      year: '2011–15',
      title: 'Path of Exile',
      meta: 'Grinding Gear Games · PC · In-house engine',
      blurb: 'Diablo-inspired online Action RPG. PC Game of the Year 2013.',
      thumb: 'assets/images/path-of-exile/path-of-exile-button-1503612705551.jpg',
      youtube: 'f1I0QSF6f94',
      highlight: true,
      rank: 95,
      involvement: 'Sole level designer from pre-alpha through release and several expansions. Created all levels — working with and refining the generation system to craft areas, rooms and topologies across diverse themes. Designed and implemented missions, quests, NPCs, dialogue and enemy encounters.',
      links: [
        { label: 'Trailer ↗', url: 'https://youtu.be/dURQBqMiwIk' },
        { label: 'Environments ↗', url: 'https://www.youtube.com/watch?v=f1I0QSF6f94' },
        { label: 'Steam ↗', url: 'https://store.steampowered.com/app/238960/Path_of_Exile/' },
      ],
      tags: ['PC', 'ARPG', 'Level Design', 'Live Service', 'Sole Designer', 'Shipped'],
    },
  ],

  personal: [
    {
      id: 'traingame',
      year: '2025',
      title: 'Train Game',
      meta: 'Personal · Unity',
      blurb: 'Carve hills and build a tramway into dense Northland forest to harvest and transport huge Kauri trees.',
      thumb: null,
      youtube: 'JZkDz6I0yVI',
      highlight: true,
      rank: 60,
      involvement: 'Solo project. In development.',
      links: [
        { label: 'Playthrough ↗', url: 'https://youtu.be/JZkDz6I0yVI' },
      ],
      tags: ['Unity', 'Solo', 'In Development'],
    },
    {
      id: 'gravityecho',
      year: '2025',
      title: 'Gravity Echo',
      meta: 'GMTK Game Jam 2025 · Web · Unity',
      blurb: 'Escape the planet before a catastrophe triggers a time loop.',
      thumb: 'assets/images/gravityecho/header.png',
      highlight: true,
      rank: 80,
      involvement: 'Team lead, design, implementation. Recruited team members from GMTK and local discords, coordinating across timezones and varied experience levels. Selected artists whose portfolios matched a specific art style vision. Reworked 3D art to make it game-ready. Wrote all code and handled most of the implementation.',
      links: [
        { label: 'Play on itch.io ↗', url: 'https://thatnzguy.itch.io/gravityecho' },
      ],
      tags: ['Game Jam', 'Unity', 'Team Lead', 'Web', 'Shipped'],
    },
    {
      id: 'traingo',
      year: '2023',
      title: 'TrainGo!',
      meta: 'Personal · Mobile AR · Unity',
      blurb: 'Lay AR tracks as you walk outdoors. Discover resources and connect your network with others.',
      thumb: null,
      youtube: 'rqEcSoAnMpo',
      highlight: false,
      rank: 30,
      involvement: 'Solo project.',
      links: [
        { label: 'Video ↗', url: 'https://youtube.com/shorts/rqEcSoAnMpo' },
      ],
      tags: ['AR', 'Mobile', 'Unity', 'Solo'],
    },
    {
      id: 'thumbsdb',
      year: '2014',
      title: 'Thumbs DB',
      meta: 'Personal · JavaScript',
      blurb: 'Processes Idle Thumbs podcast timestamps into searchable topic summaries. Featured on the podcast.',
      thumb: null,
      youtube: 'Kiu1ty6GrGM',
      highlight: false,
      rank: 10,
      involvement: 'Solo — final project for Harvard CS 101. Pulls data from the Idle Thumbs YouTube channel and processes timestamps to create topics with summaries.',
      links: [
        { label: 'Video ↗', url: 'https://youtu.be/Kiu1ty6GrGM' },
        { label: 'GitHub ↗', url: 'https://github.com/thatnzguy/thumbsdb' },
      ],
      tags: ['JavaScript', 'Web', 'Solo'],
    },
    {
      id: 'windowmod',
      year: '2018',
      title: 'Window Resize Mod',
      meta: 'Personal · Stardew Valley · SMAPI',
      blurb: 'Stardew Valley mod enabling window resizing for splitscreen before official support was added.',
      thumb: null,
      highlight: false,
      rank: 5,
      involvement: 'Solo. Learning code injection using decompiled game code for reference.',
      links: [
        { label: 'Nexus Mods ↗', url: 'https://www.nexusmods.com/stardewvalley/mods/2266' },
      ],
      tags: ['Modding', 'SMAPI', 'Solo', 'C#'],
    },
    {
      id: 'vigilance',
      year: '<2007',
      title: 'dod_vigilance',
      meta: 'Day of Defeat · PC · Source',
      blurb: 'Custom WWII FPS map. 70,000+ downloads. Top 10 most-played DoD custom maps.',
      thumb: 'assets/images/maps/vigilance_overview.jpg',
      youtube: 'shRhWy4hro4',
      highlight: true,
      rank: 50,
      involvement: 'Solo development. Created for both the Half-Life 1 mod Day of Defeat and the Half-Life 2 mod Day of Defeat: Source. Accumulated over 70,000 downloads and ranked among the top 10 most-played custom maps in the community.',
      links: [
        { label: 'Trailer ↗', url: 'https://www.youtube.com/watch?v=shRhWy4hro4' },
      ],
      tags: ['Level Design', 'Source', 'Solo', 'Modding', 'Community'],
    },
  ],
};
